### ISSUE TITLE
Update TZDB to 2019a

### ISSUE THREAD

**Issue by drewhamilton** [JakeWharton/ThreeTenABP#105]
ThreeTenBP has been updated to timezone database 2019a. Is updating ThreeTenABP to the same tzdb as simple as copying the .dat file from [here](https://github.com/ThreeTen/threetenbp/tree/master/src/main/resources/org/threeten/bp) into this library?

**Comment by jemaystermind** [comment]
You might want to check #104.

**Comment by drewhamilton** [comment]
@jemaystermind Thanks for the reference, I hadn't seen that. I won't go ahead with my own PR for this then.

That said, it looks like ThreeTenBP *has* released with 2019a so Jake can now as well.

**Comment by JakeWharton** [comment]
Been on vacation. It's on my backlog.
