### ISSUE TITLE
Unable to use dateformatter

### ISSUE THREAD

**Issue by cromulent-coder** [JakeWharton/ThreeTenABP#111]
Unable to use dateformatter for formatting date of this particular format 'yyyy-MM-dd'T'HH:mm:ss.SSSSSS'

**Comment by JakeWharton** [comment]
Please provide a failing test case or example that reproduces the problem.

**Comment by cromulent-coder** [comment]
`
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS");
LocalDateTime localDateTime = LocalDateTime.parse(dateString, formatter);
`
Date String is: 2019-08-16T18:57:32.071016+05:30

org.threeten.bp.format.DateTimeParseException: Text '2019-08-16T18:57:32.071016+05:30' could not be parsed at index 26

**Comment by mariushorvat** [comment]
@JakeWharton 
Could you please let us know of  you had the chance to fix this issue:
Fatal Exception: org.threeten.bp.format.DateTimeParseException: Text '2019-10-20T00:00:00.000Z' could not be parsed, unparsed text found at index 23

Our  app is crashing for more than 2000. Any work around?

Thanks!

**Comment by JakeWharton** [comment]
Your input string contains a timezone offset but your format string does not account for that. Index 26 is the plus character which starts the offset.
