### ISSUE TITLE
Update tzdb.dat to new version.

### ISSUE THREAD

**Issue by 0megaD** [JakeWharton/ThreeTenABP#116]
I had some issues with Brazil not going to DST this year in november, but the latest dat file in your repo doesn't reflect that change.

As such, here's the latest tzdb.dat file (rename .txt to .dat, github doesn't like .dat files):
Alternatively, run Oracle's timezone tool to get the latest .dat file.

[tzdb.txt](https://github.com/JakeWharton/ThreeTenABP/files/3859418/tzdb.txt)

**Comment by JakeWharton** [comment]
This project tracks the TZDB from [ThreeTenBP](https://github.com/ThreeTen/threetenbp). If you would like a new TZDB and a release, the first step is to land it in that project.

Additionally, since version 1.2.0 you can embed your own TZDB in your assets and use the two-argument constructor.

**Comment by yccheok** [comment]
@JakeWharton 

Do you mean we can pick up this file without modification, and place it in our own project as asset?

https://github.com/ThreeTen/threetenbp/blob/master/src/main/resources/org/threeten/bp/TZDB.dat

But, according to https://github.com/ThreeTen/threetenbp/issues/106 , the pointed TZDB is not yet updated with Brazil latest DST change.

**Comment by 0megaD** [comment]
@yccheok 
It means that if we want the updated tzdb.dat file in this project, you have to make ThreeTenBP also take the newest TZDB.dat file. As you mentioned they didn't update it yet, so if you want them to fix it you have to wait.

Otherwise, follow the following instructions:
1.) Download tzdb.txt file from my comment.
2.) Rename to tzdb.dat
3.) Put in android asset folder.
4.) Call constructor with custom file parameter: AndroidThreeTen.init(this, "tzdb.dat")
5.) Done!

If you want to generate your own tzdb.dat file, use the tool from oracle.
https://www.oracle.com/technetwork/java/javase/documentation/tzupdater-readme-136440.html
