### ISSUE TITLE
minusDays() returns wrong date for specific use case

### ISSUE THREAD

**Issue by deepakmn86** [JakeWharton/ThreeTenABP#120]
minusDays() returns wrong date for below specific use case

**Version: v1.2.1**

**Code to reproduce:**
```
val date = LocalDate.of(2020, 1, 13).minusMonths(1)
val lastDate = date.withDayOfMonth(date.lengthOfMonth())
val dateStr = DateTimeFormatter.ofPattern("MMMM dd YYYY").format(lastDate)
```

**Expected:**
dateStr must be "December 31 2019"

**Actual:**
dateStr is "December 31 2020"

**Comment by deepakmn86** [comment]
Weird, It seems to work fine if I use ""MMMM dd **yyyy**""instead of "MMMM dd **YYYY**".
Closing the issue.

**Comment by dlew** [comment]
This video explains what's going on: https://www.youtube.com/watch?v=D3jxx8Yyw1c
