### ISSUE TITLE
R8 issue with Ser

### ISSUE THREAD

**Issue by eygraber** [JakeWharton/ThreeTenABP#122]
It looks like the public constructor is getting stripped.

Our solution is:

```
-keepclassmembers class org.threeten.bp.Ser {
    <init>();
}
```

but not sure if more would need to be done.

**Comment by wbervoets** [comment]
I can verfiy that the above solution is working. 
I'm using the R8 version bundled with Android Studio 3.6.0

**Comment by JakeWharton** [comment]
We should see if threetenbp would ship rules inside their jar before adding to this library. Does anyone want to file an issue upstream?

**Comment by JakeWharton** [comment]
Which type were you serializing when you ran into this? I'm trying to write a test for it.

We actually already have a serialization test for `ZonedDateTime` passing through Java serialization in a build with minification enabled because there was an issue once where it lost information.

**Comment by eygraber** [comment]
I believe it was `LocalTime`

**Comment by JakeWharton** [comment]
I cannot reproduce the crash. What version of AGP are you on?

**Comment by eygraber** [comment]
We've had the proguard rule in for a while now. I can dig and see what version we were on when the bug was filed.

**Comment by JakeWharton** [comment]
Thanks. I might just ship the update which bumps the threetenbp without a regression test. I expect this project to enter maintenance mode with AGP 4.0 shipping desugaring of `java.time` anyway. This project is already low-overhead so it's not like things are changing rapidly.

**Comment by eygraber** [comment]
Yeah we're hoping to start relying on the desugaring once AGP 4 is stable.

**Comment by JakeWharton** [comment]
I would _strongly_ recommend someone trying it ASAP while problems can still be addressed. It's already getting late in the 4.0 cycle. You should be able to mass replace imports and smoke test is fairly quickly.

**Comment by JakeWharton** [comment]
Are you running R8 in full mode?

**Comment by JakeWharton** [comment]
Reproduced!

**Comment by JakeWharton** [comment]
AGP 3.6 and R8 full mode causes the existing serialization test to fail because of `Ser`'s missing ctor (on 1.4.1). Bumping to 1.4.2 fixes it.

**Comment by wbervoets** [comment]
Sorry I'm too late commenting... :) I indeed had the issue on AGP 3.6.x and R8 full mode enabled on 1.4.1

**Comment by eygraber** [comment]
We also use full mode. 

And the java.time desugaring seems to be working well.

**Comment by calmmycode** [comment]
Same problem with:
`E/AndroidRuntime(13190): java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Period;`
