### ISSUE TITLE
Will we still need this library after java.time will be desugared?

### ISSUE THREAD

**Issue by kamerok** [JakeWharton/ThreeTenABP#124]
One of the features of Android Studio 4.0 is [desugaring a subset of `java.time`](https://developer.android.com/studio/preview/features/#j8-desugar)
It's mistery for me what subset is being desugared exactly. But if it will be enough to replace ThreeTen will we still need a different way of loading timezone information?

**Comment by kamerok** [comment]
Sorry, found the answer https://github.com/JakeWharton/ThreeTenABP/issues/92

**Comment by vinaysshenoy** [comment]
> One of the features of Android Studio 4.0 is [desugaring a subset of `java.time`](https://developer.android.com/studio/preview/features/#j8-desugar)
> It's mistery for me what subset is being desugared exactly. But if it will be enough to replace ThreeTen will we still need a different way of loading timezone information?

@kamerok I was having trouble finding the exact feature set being desugared. Found it over here: https://developer.android.com/studio/write/java8-support-table.

**Comment by kamerok** [comment]
@vinaysshenoy thank you that's helpful!

Offtopic question: have you tried migrating from ThreeTen? If so, how was your experience?

**Comment by vinaysshenoy** [comment]
> @vinaysshenoy thank you that's helpful!
> 
> Offtopic question: have you tried migrating from ThreeTen? If so, how was your experience?

We haven't migrated yet. We added desugaring support very recently and we're just working on [migrating](https://github.com/simpledotorg/simple-android/issues/1381) our internal `Optional` implementation to the Java 8 Optional. We will think of migrating threetenbp after.

**Comment by vinaysshenoy** [comment]
@kamerok We migrated here: https://github.com/simpledotorg/simple-android/pull/1479

Was pretty much painless, only required a search and replace. All tests were green, on both API 21 (min SDK) and latest.

**Comment by kamerok** [comment]
@vinaysshenoy thank you for reaching out!
We are waiting until [fixed lint](https://issuetracker.google.com/issues/158189490) will reach stable android studio. As I can see you were not affected by this because you don't have pure kotlin modules with java.time
