### ISSUE TITLE
Do I actually want to switch to desugared native apis?

### ISSUE THREAD

**Issue by ursusursus** [JakeWharton/ThreeTenABP#127]
Hi, I see the note in the readme as to switch to the native apis via L8

However, timezone data is now baked into the os, right?

Do I want that?

**Comment by JakeWharton** [comment]
https://source.android.com/devices/tech/config/timezone-rules

**Comment by JakeWharton** [comment]
Timezone data updates out-of-band with the OS.

**Comment by ursusursus** [comment]
Hold on, isnt that 8.1+?

**Comment by JakeWharton** [comment]
Yes. If you want to bundle your own timezone data you are still free to. The process of installing them is exactly the same as the mechanism this library uses.

**Comment by ursusursus** [comment]
Would you recommend doing that? Not sure if it is cool to leave say Android 5' with its platform tz data if I were to simply swap imports to `java.time`

**Comment by JakeWharton** [comment]
I mean ultimately those TZ rules are going to be what's used by `Date` and `Calendar` and the OS itself, so there's local consistency. I think it's a trade-off that you have to decide on.

Ultimately I'm going to publish updates to the tzdb in this project for as long as it's easy. So not switching is also an option.

**Comment by ursusursus** [comment]
Right, guess I'll stay until minSdk 26 is a thing, not much reason to switch. Thanks
