### ISSUE TITLE
Help for specific pattern

### ISSUE THREAD

**Issue by SaeedNoshadi89** [JakeWharton/ThreeTenABP#132]
Hi,
how can I parse this DateTime format?

Wed Feb 03 2021 08:40:44 GMT+08:00

to 

Wed 03 Feb 2021 08:40:44 am

**Comment by JakeWharton** [comment]
Please ask general usage questions for ThreeTenBP / java.time on StackOverflow. There's nothing specific to ThreeTenABP in your question, and StackOverflow serves as a better record of questions and answers than here for future travelers.
