### ISSUE TITLE
Returns the Value to 1926

### ISSUE THREAD

**Issue by naufalprakoso** [JakeWharton/ThreeTenABP#137]
Hi, I have an issue with this library in my application. When using this library, sometimes it returns 1920-1926 years. Anyone familiar with this?

**Comment by JakeWharton** [comment]
Please provide a sample that reproduces the behavior of an executable test case. Otherwise it's impossible to know what's going wrong.

**Comment by naufalprakoso** [comment]
Currently, I'm using this method `OffsetDateTime.now()` and sometimes our user got 1920 years in their date time.

**Comment by JakeWharton** [comment]
Not sure. Sounds like maybe the time zone database isn't being loaded correctly.
