### ISSUE TITLE
Please *do not* consider switching to core library desugaring

### ISSUE THREAD

**Issue by filipebrandao** [JakeWharton/ThreeTenABP#138]
I just want make people aware that this project should still be standard and encouraged for date and time apis in Android. Specially for date/time sensitive apps across different timezones.

My experience with using `ZonedDateTime` with core library desugaring was not so good. Personally I decided to not use TrheeTenABP because of this statement in the README which sounded totally fair:
> Attention: Development on this library is winding down. Please consider switching to Android Gradle plugin 4.0, java.time.*, and its [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) feature in the coming months.

By following the desugaring path, I had issues because of outdated timezones database in older devices. One example is the timezone `America/Sao_Paulo` where DST was abolished in Brazil back in 2019 but so many devices are still not aware of timezone changes and will never be. But ThreeTen provides updated timezones database and fixes this issue in any device.

Folks at kotlinx-datetime [also face the same problems](https://github.com/Kotlin/kotlinx-datetime/issues/201) and that's why I think the usage of this ThreeTenABP project should still be encouraged for date and time apis in Android.

**Comment by JakeWharton** [comment]
Desugaring supports shipping a custom tzdb the same way this library does. The only difference is now you are responsible for updating it rather than me.

**Comment by filipebrandao** [comment]
Further note for people falling in this same issues who still want to keep using google's unofficial desugaring lib: There's a project that  accomplishes Jake's suggestion and can be a good starting point https://github.com/ZacSweers/ticktock 

Personally, given the option, I would still consider using ThreeTenABP instead.
