### ISSUE TITLE
Fatal Exception: n30.g Unknown time-zone ID: America/Ciudad_Juarez

### ISSUE THREAD

**Issue by sureshmaidaragi1** [JakeWharton/ThreeTenABP#139]
Hi There our app is crashing due to Unknown time-zone ID: America/Ciudad_Juarez

```
Fatal Exception: n30.g: Unknown time-zone ID: America/Ciudad_Juarez
       at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:167)
       at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:122)
       at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
       at org.threeten.bp.ZoneId.of(ZoneId.java:358)
       at org.threeten.bp.ZoneId.of(ZoneId.java:286)
       at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:245)
```

Can someone help to check. Looks like t[his is new timezone added recently ](http://mm.icann.org/pipermail/tz-announce/2022-November/000076.html)

I am using in android with the dependency 

`com.jakewharton.threetenabp:threetenabp:1.4.3
`

**Comment by JakeWharton** [comment]
See https://github.com/ThreeTen/threetenbp/issues/178 and https://github.com/ThreeTen/threetenbp/issues/175#issuecomment-1321756868. You likely are mixing and matching the tzdb of the system with the tzdb of this library which are not guaranteed to be in sync.

**Comment by sureshmaidaragi1** [comment]
@JakeWharton as mentioned in the thread you linked, we explicitly dont use them, just we use your dependency 

https://github.com/ThreeTen/threetenbp/issues/175#issuecomment-1445336702.

Just rewriting it if I update to the latest threeten dependency would it solves the problem?

**Comment by JakeWharton** [comment]
This library is only a repackaging of the timezone database from ThreeTenBP so if you use this library you also use that library. I have no idea if updating will fix your issue. You would have to check to see what version of the timezone database added that ID and whether ThreeTenBP and this library have had a release which includes it. Beyond that, though, you have a wider problem of dealing with two sources of a timezone database that are not in-sync and this likely will happen again in the future.
