### ISSUE TITLE
Unit testing?

### ISSUE THREAD

**Issue by tadfisher** [JakeWharton/ThreeTenABP#14]
Is Robolectric a requirement for loading a `ZoneInfoProvider`? Could there be a mechanism for loading such that doesn't depend on Android APIs?

**Comment by anothem** [comment]
I've done this by using the standard JVM backport package for unit testing. 
`testCompile 'org.threeten:threetenbp:1.3.1'`

Still experimenting, but haven't run into any issues so far.

**Comment by JakeWharton** [comment]
:+1:

**Comment by tadfisher** [comment]
Thanks! WFM.

**Comment by emartynov** [comment]
I'm getting:
```org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered

	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:176)
	at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:133)
	at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
	at org.threeten.bp.ZoneId.of(ZoneId.java:357)
	at org.threeten.bp.ZoneId.of(ZoneId.java:285)
	at org.threeten.bp.ZoneId.systemDefault(ZoneId.java:244)
	at org.threeten.bp.Clock.systemDefaultZone(Clock.java:137)
	at org.threeten.bp.LocalDate.now(LocalDate.java:165)
        ...```

**Comment by andretietz** [comment]
Same issue here, even with jvm backport (version 1.0.3 using AS 2.2 P7)

**Comment by kiwiandroiddev** [comment]
@emartynov @andretietz I was having the same issue even after including the jvm backport. Manually deleting the contents of the build directory and re-reunning the Junit test resolved it for me...

**Comment by hohnamkung** [comment]
`org.threeten.bp.zone.ZoneRulesException: No time-zone data files registere` exception happens because project is depending on [no no-tzdb jar in test project](https://github.com/JakeWharton/ThreeTenABP/blob/master/threetenabp/build.gradle#L4).
Making sure your test project to depend jar which contains timezone db in testCompile may solve this problem.

**Comment by anothem** [comment]
If you are (also) running unit tests with Robolectric and using the JVM backport, make sure that you aren't calling `AndroidThreeTen.init(this)`.

**Comment by vdubedout** [comment]
To resume for people passing around.

app/build.graddle 
```
dependencies {
    [...]
    compile 'com.jakewharton.threetenabp:threetenabp:1.0.4'
    testCompile ('org.threeten:threetenbp:1.3.2'){
        exclude group:'com.jakewharton.threetenabp', module:'threetenabp'
    }
    testCompile('org.robolectric:robolectric:3.1.2') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
    [...]
}
```

Test class
```
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21, application = TestApp.class)
public class MessagingTimeFormatterTest {
    [...]
}
```

TestApp without ```AndroidThreeTen.init(this)```
```
public class TestApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
    }
}
```

-> clean & build

**Comment by ansf** [comment]
Thanks!
Should we add that information to the readme?

**Comment by gotev** [comment]
I have both unit and instrumented android tests.

None of the above mentioned solutions worked in my case. I don't use RoboElectric. Even gradle exclusion stragies through transitive dependencies and configuration failed.

But thanks to this article: https://pbochenski.pl/blog/04-14-2017-testing-three-ten-abp.html

I came to a definitive solution.

`build.gradle`:
```
implementation "com.jakewharton.threetenabp:threetenabp:1.2.2"
```

Download [this](https://github.com/JakeWharton/ThreeTenABP/raw/master/threetenabp/src/main/assets/org/threeten/bp/TZDB.dat) to your `project/src/test/resources` directory.

`AndroidTestDateExtensions.kt`
```kotlin
import androidx.test.platform.app.InstrumentationRegistry
import com.jakewharton.threetenabp.AndroidThreeTen

fun initAndroidThreeTen() {
    val appContext = InstrumentationRegistry.getInstrumentation().targetContext.applicationContext
    AndroidThreeTen.init(appContext)
}
```

`UnitTestDateExtensions.kt`
```kotlin
import org.threeten.bp.zone.TzdbZoneRulesProvider
import org.threeten.bp.zone.ZoneRulesProvider

fun Any.initThreeTen() {
    if (ZoneRulesProvider.getAvailableZoneIds().isEmpty()) {
        val stream = this.javaClass.classLoader!!.getResourceAsStream("TZDB.dat")
        stream.use(::TzdbZoneRulesProvider).apply {
            ZoneRulesProvider.registerProvider(this)
        }
    }
}
```

`UnitTest.kt`
```kotlin
class MyUnitTest {

    init {
        initThreeTen()
    }

    @Test
    fun `awesome unit test`() {
    }
}
```

`InstrumentationTest.kt`
```kotlin
@RunWith(AndroidJUnit4::class)
class MyInstrumentationTest {
    @Before
    fun setUp() {
        initAndroidThreeTen()
    }

    @Test
    fun awesomeInstrumentationTest() {
    }
}
```

**Comment by GitHubMurt** [comment]
@gotev although it works with unit test if You don't forteg to use 
`testImplementation 'org.threeten:threetenbp:1.4.0'`

for AndroidTest it throws me error after first @Test that is using to DateTimeUtil 
java.lang.RuntimeException: Delegate runner 'androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner' for AndroidJUnit4 could not be loaded.
