### ISSUE TITLE
Wrong timezone for Almaty

### ISSUE THREAD

**Issue by drelagreen** [JakeWharton/ThreeTenABP#146]
Almaty timezone since 2024 - UTC+5
Almaty timezone in the library - UTC+6

**Comment by JakeWharton** [comment]
All timezone information comes from the ThreeTenBP library here: https://github.com/ThreeTen/threetenbp/. If you are having problems with the it you can file an issue on that project for it to update the data.

This project only repackages that one to work more efficiently on Android but does not contribute or control any actual behavior.
