### ISSUE TITLE
Documentation missing?

### ISSUE THREAD

**Issue by thalesmello** [JakeWharton/ThreeTenABP#15]
I've installed this package successfully in my Android project. The problem is that I get no documentation when I use the quick reference (F1) on Android Studio.

From a quick google search, I've found the original [org.threeten.bp documentation](http://www.threeten.org/threetenbp/apidocs/). Is it possible to have that accessible from Android Studio?

**Comment by JakeWharton** [comment]
The reason is that we depend on a specific artifact of ThreeTen instead of the normal one, so the sources can't be downloaded automatically. Maybe file a bug on http://b.android.com for AS to add support for that behavior? In any case, there's nothing that can be done from this project about it.
