### ISSUE TITLE
ThreeTen is ignoring Android 24/12 hour display settings

### ISSUE THREAD

**Issue by rnevet** [JakeWharton/ThreeTenABP#16]
When trying to print `ZoneDateTime` time using `DateTimeFormatter`, the user system settings regarding 24/12 hour display is ignored

The issue is if you use:
`DateTimeFormatter timeFormat = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT);`

The time format will only consider the Locale and not the user settings, example:
DE Locale will display a 24Hours format: 23:30
EN Locale will display a 12Hours format: 11:30 PM
Regardless of the user system settings.

android.text.DateFormat.getTimeFormat(Context context) will take the system settings in consideration but only accepts Date objects, the conversion isn't straight forward and might lead to mistakes.

**Comment by rnevet** [comment]
This is how I bypassed this issue for now:
'''java
    public static String formatTime(ZonedDateTime zdt, Context context) {
        java.text.DateFormat timeFormat = android.text.format.DateFormat.getTimeFormat(context);
        int hour = zdt.getHour();
        int min = zdt.getMinute();
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, hour);
        cal.set(Calendar.MINUTE, min);
        return timeFormat.format(cal.getTime());
    }
'''

**Comment by JakeWharton** [comment]
The library knows nothing about Android, so yes, it is. I'll see if there's hooks.

There's [`DateFormat.is24HourFormat`][1] for checking more easily and switching between two formats as a potentially easier workaround.

**Comment by JakeWharton** [comment]
So this is pluggable internally, but there's no public API to hook into this.

**Comment by JakeWharton** [comment]
I think we might have to just provide `AndroidDateTimeFormatter` in the library.

**Comment by rnevet** [comment]
I researched it deeper as well, couldn't find anyway to change this behavior internally. 

I have another possible solution, but I think it's a bit riskier then my first one:
```Java
    public static String formatTime(ZonedDateTime zdt, Context context) {
        java.text.DateFormat timeFormat = DateFormat.getTimeFormat(context);
        Instant instant = zdt.toInstant();
        long millisecondsSinceEpoch = instant.toEpochMilli();  // Data-loss, going from nanosecond resolution to milliseconds.
        Date date = new Date(millisecondsSinceEpoch);
        timeFormat.setTimeZone(getTimeZone(zdt.getZone()));
        return timeFormat.format(date);
    }

    private static TimeZone getTimeZone(ZoneId zoneId) {
        String tzid = zoneId.getId(); // throws an NPE if null
        char c = tzid.charAt(0);
        if (c == '+' || c == '-') {
            tzid = "GMT" + tzid;
        } else if (c == 'Z' && tzid.length() == 1) {
            tzid = "UTC";
        }
        return TimeZone.getTimeZone(tzid);
    }
```

I copied the getTimeZone function from Java 8 implementation with a small adjustment, 
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/TimeZone.java#TimeZone.getTimeZone%28java.time.ZoneId%29
TimeZone.getTimeZone in the Java 8 implementation has a fallback option. i.e. there might be a situation where this might fail? not sure.

**Comment by rnevet** [comment]
I found a better solution IMO,
```
    public static String formatTime(ZonedDateTime zdt, Context context) {
        SimpleDateFormat sdf = (SimpleDateFormat) android.text.format.DateFormat.getTimeFormat(context);
        DateTimeFormatter format = DateTimeFormatter.ofPattern(sdf.toPattern());
        return format.format(zdt);
    }
```

**Comment by tobiasschuerg** [comment]
I'm also facing this issue. The solution of @rnevet from nov '15 seems ok, although I would prefer something which isn't directly tied to the current Context. Is this still the way to go?

Wouldn't it be nice to do this automatically during ` AndroidThreeTen.init(this);` and persist?

**Comment by JakeWharton** [comment]
See: https://github.com/JakeWharton/ThreeTenABP/pull/103#issuecomment-498429319
