### ISSUE TITLE
wrong year with DateTimeFormatter

### ISSUE THREAD

**Issue by the4thfloor** [JakeWharton/ThreeTenABP#19]
When I use the DateTimeFormatter I get a wrong year for the first days of the new year

```java
public class BugTest {

    private final static DateTimeFormatter full = DateTimeFormatter.ofPattern("dd-MMM-YYYY");
    private final static DateTimeFormatter yyyy = DateTimeFormatter.ofPattern("YYYY");

    public static void testYear() {

        print(StringExtensionsKt.convertToDate("2015-12-31T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-01T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-02T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-03T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-04T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-05T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-06T12:00:00+0200"));
        print(StringExtensionsKt.convertToDate("2016-01-07T12:00:00+0200"));
    }

    private static void print(OffsetDateTime dateTime) {

        Timber.i("dateTime: %s full: %s year1: %s year2: %d",
                dateTime, full.format(dateTime), yyyy.format(dateTime), dateTime.getYear());
    }
}
```

prints the following

```
dateTime: 2015-12-31T12:00+02:00 full: 31-Dez.-2015 year1: 2015 year2: 2015
dateTime: 2016-01-01T12:00+02:00 full: 01-Jan.-2015 year1: 2015 year2: 2016
dateTime: 2016-01-02T12:00+02:00 full: 02-Jan.-2015 year1: 2015 year2: 2016
dateTime: 2016-01-03T12:00+02:00 full: 03-Jan.-2015 year1: 2015 year2: 2016
dateTime: 2016-01-04T12:00+02:00 full: 04-Jan.-2016 year1: 2016 year2: 2016
dateTime: 2016-01-05T12:00+02:00 full: 05-Jan.-2016 year1: 2016 year2: 2016
dateTime: 2016-01-06T12:00+02:00 full: 06-Jan.-2016 year1: 2016 year2: 2016
dateTime: 2016-01-07T12:00+02:00 full: 07-Jan.-2016 year1: 2016 year2: 2016
```

From 01-Jan to 03-Jan it has the wrong year. I don't know where it comes from.

```java
private val DATE_FORMATTER = DateTimeFormatter.ISO_DATE
private val DATE_TIME_FORMATTER = DateTimeFormatter.ISO_DATE_TIME
private val DATE_TIME_ZONE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZZ")

fun String.convertToDate(): OffsetDateTime {

    try {
        return OffsetDateTime.parse(this, DATE_TIME_ZONE_FORMATTER)
    } catch (ignored: DateTimeParseException) {
    }

    try {
        return OffsetDateTime.of(LocalDateTime.parse(this, DATE_TIME_FORMATTER), ZoneOffset.ofTotalSeconds(0))
    } catch (ignored: DateTimeParseException) {
    }

    return OffsetDateTime.of(LocalDate.parse(this, DATE_FORMATTER).atTime(0, 0, 0, 0), ZoneOffset.ofTotalSeconds(0))
}
```

**Comment by mattprecious** [comment]
You're using both `YYYY` and `yyyy` in your formatters which are different things. `yyyy` is the "week year" which you probably don't want. 

> A week year is in sync with a WEEK_OF_YEAR cycle. All weeks between the first and last weeks (inclusive) have the same week year value. Therefore, the first and last days of a week year may have different calendar year values.
> 
> For example, January 1, 1998 is a Thursday. If getFirstDayOfWeek() is MONDAY and getMinimalDaysInFirstWeek() is 4 (ISO 8601 standard compatible setting), then week 1 of 1998 starts on December 29, 1997, and ends on January 4, 1998. The week year is 1998 for the last three days of calendar year 1997. If, however, getFirstDayOfWeek() is SUNDAY, then week 1 of 1998 starts on January 4, 1998, and ends on January 10, 1998; the first three days of 1998 then are part of week 53 of 1997 and their week year is 1997.
http://docs.oracle.com/javase/7/docs/api/java/util/GregorianCalendar.html#week_year

**Comment by JakeWharton** [comment]
Yep. `YYYY` is "week year" though. See https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns for formats.

Also this library doesn't really do anything. Just adapt another library, [ThreeTenBP][1], which is where you would want to file actual issues.

 [1]: https://github.com/ThreeTen/threetenbp

**Comment by the4thfloor** [comment]
thanks a lot :-)
