### ISSUE TITLE
Cannot compile project

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/ThreeTenABP#2]
Hi,
I am trying to include this library in my project.  But I get a stacktrace every time:
> Error:Could not find org.threeten:threetenbp:1.3-SNAPSHOT.
Required by:
    :app:unspecified > com.jakewharton.threetenabp:threetenabp:1.0.0-SNAPSHOT

**Comment by JakeWharton** [comment]
You need the 1.3-SNAPSHOT of the `notzdb` branch of the [ThreeTenBP][1] project.

 [1]: https://github.com/ThreeTen/threetenbp

**Comment by IgorGanapolsky** [comment]
I don't understand.  I added the following:
`compile 'com.jakewharton.threetenabp:threetenabp:1.0.0-SNAPSHOT'
 compile 'org.threeten:threetenbp:1.3-SNAPSHOT'
`

Please advise.

**Comment by Giszmo** [comment]
I feel with @IgorGanapolsky here. "A snapshot is available in the Sonatype snapshot repo" was totally zero information for me and googling for 20 minutes didn't yield any pointers on how to get kotterknife working. No clue which universal knowledge I'm lacking here but I'd be glad if somebody could expand the README.md on that part cause it's very very frustrating and I bet I'm not the only stupid dev who would appreciate a plug and play solution.
