### ISSUE TITLE
No timezone data files registered

### ISSUE THREAD

**Issue by sreejithraman** [JakeWharton/ThreeTenABP#21]
Why would I be getting this? Are the time zone rules not part of the package?
This is the error I get:
`System.err: org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered`
Here is my code:
````Java
DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss VV", Locale.ENGLISH)
                .withZone(ZoneId.of(cruiseShipEntity.getDateBuilt().getTimeZone()));
ZonedDateTime dateBuilt = ZonedDateTime.parse("2012-06-03 00:00:00 America/New_York", dateTimeFormatter);
````

**Comment by JakeWharton** [comment]
Did you call `init`?

**Comment by sreejithraman** [comment]
Wow... I'm an idiot. I swear I did it but I guess not. I'm going to go ahead and close this.

**Comment by JakeWharton** [comment]
No worries. It's an unfortunate precondition.

**Comment by emartynov** [comment]
@JakeWharton, what about unit test on JVM? How to bypass this exception?

**Comment by scottyab** [comment]
@emartynov i just came across this. the solution I used was to use the java version for the tests. i.e.

`testCompile 'org.threeten:threetenbp:1.3.5'`

**Comment by emartynov** [comment]
Thank you!
