### ISSUE TITLE
AS firing sources for 'threetenbp-1.3.1-no-tzdb.jar' not found

### ISSUE THREAD

**Issue by ar-g** [JakeWharton/ThreeTenABP#22]
AS firing sources for 'threetenbp-1.3.1-no-tzdb.jar' not found. Because of this, it's impossible to see javaDocs

**Comment by MenoData** [comment]
Sounds like a duplicate of https://github.com/JakeWharton/ThreeTenABP/issues/15

**Comment by ar-g** [comment]
You're right, closing. I'm using for testing purpose dependency  testCompile 'org.threeten:threetenbp:1.3.1' so can browse and see docs
