### ISSUE TITLE
Why is `minSdkVersion` set to 15? Could it be lower?

### ISSUE THREAD

**Issue by cookingfox** [JakeWharton/ThreeTenABP#28]
Hi,

I was just wondering: why is `minSdkVersion` set to 15? Is it possible to set it lower?
I'm working on a library which depends on ThreeTenABP and noticed I had to bump up the version just to support it.

Thanks!

Abel
Cooking Fox

**Comment by plastiv** [comment]
It is a duplicate. Check answers here:

* https://github.com/JakeWharton/ThreeTenABP/issues/20
* https://github.com/JakeWharton/ThreeTenABP/issues/8

**Comment by JakeWharton** [comment]
You can [use the `tools:overrideLibrary` attribute to override this][1], but for 99.99% of developers a minimum of 15 is sufficient, and you should consider doing the same for your library.

 [1]: http://stackoverflow.com/a/27310430/132047
