### ISSUE TITLE
LocalDate.format returning invalid result

### ISSUE THREAD

**Issue by gborland** [JakeWharton/ThreeTenABP#33]
I haven't been able to reproduce this myself, but I am getting reports from the wild that sometimes `LocalDate.format()` is returning an invalid result.

Here's what happens, as confirmed by the log call in this method and reported via Crashlytics. 
- On entry to this method, `month` is `2016-08`.
- `startOfMonth` is correctly set to `2016-08-01`.
- `monthString` gets set to `0000-00-00` which is wrong.

```java
private Observable<Void> ensureDataForMonthExistsInternal(YearMonth month) {
    final LocalDate startOfMonth = month.atDay(1);
    final String    monthString  = startOfMonth.format(DateTimeFormatter.ISO_LOCAL_DATE);
    Timber.i("Calling ensureDataForMonthExists with month %s, as date %s, formatted %s", month, startOfMonth, monthString);
```

The only thing I can think of is that this happens as part of the app startup sequence, so maybe AndroidThreeTen isn't fully initialised at this point? It looks as though `AndroidThreeTen.init()` should be synchronous, though, and this all happens after `AndroidThreeTen.init()` has returned.

Is there some aspect of AndroidThreeTen which is not fully synchronous?

Here's how I'm calling `AndroidThreeTen.init()`. It's almost the first thing in my `Application.onCreate()`, long before the failing sequence of events gets triggered.

```java
@Override
public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics.Builder().core(new CrashlyticsCore.Builder().disabled(BuildConfig.DEBUG).build()).build());
    AndroidThreeTen.init(this);

    // other init

    // call failing sequence shown above
}
```

Reports are coming in from a small percentage of users, which suggests to me it's a timing issue rather than a fundamental problem with the logic.

**Comment by gborland** [comment]
Looking at it some more, I can't see how this can be a timing issue. All the crash reports seem to be coming from Moto devices running Android 6.0, so maybe ThreeTenBp itself is using some system APIs for date formatting which are broken on Motorola devices.

@JakeWharton if you concur, I'll close this and re-open directly on https://github.com/ThreeTen/threetenbp although I don't expect they'd be able to do much about it.

**Comment by JakeWharton** [comment]
It seems very unlikely to be a problem in this library since all it does it load the TZDB.dat from a different source. Everything else is just the normal ThreeTenBP code running.

I would file an issue on ThreeTenBP for this. I'm not super familiar with its internals beyond the timezone loading aspects to know from where a problem like this could arise.

**Comment by gborland** [comment]
Thanks, reported as https://github.com/ThreeTen/threetenbp/issues/50. I'll close this one.
