### ISSUE TITLE
AndroidThreeTen.init should take Context instead of Application

### ISSUE THREAD

**Issue by consp1racy** [JakeWharton/ThreeTenABP#34]
Only use:

      InputStream is = application.getAssets().open("org/threeten/bp/TZDB.dat");

Preferred alternative:

      InputStream is = context.getApplicationContext().getAssets().open("org/threeten/bp/TZDB.dat");

**Comment by JakeWharton** [comment]
The reference is not retained so there's no point in changing this.

**Comment by consp1racy** [comment]
Understood, however that's not the reason. If I wanted to call it from say a ContentProvider I'd like to avoid casting.

**Comment by JakeWharton** [comment]
I see. Makes sense.
