### ISSUE TITLE
Next Release? 

### ISSUE THREAD

**Issue by Gregliest** [JakeWharton/ThreeTenABP#37]
Any word on when the next release will be?  I'd love to have access to the updated 1.3.2 version for this [fix](https://github.com/ThreeTen/threetenbp/commit/006216f278916563c0c6c53c5e4dc4f45ff924fe).  Thanks!

**Comment by JakeWharton** [comment]
You can explicitly depend on that version from threetenbp to get newer versions, just make sure you depend on the no-tzdb variant. See the build.gradle for how to declare it.

**Comment by Gregliest** [comment]
Great, so do I keep this library for the time zone database?

**Comment by JakeWharton** [comment]
Yes you declare both. But by declaring the newer version of threetenbp directly you get its newer code and that bug fix.

**Comment by Gregliest** [comment]
Awesome, thanks.

**Comment by JakeWharton** [comment]
Releasing 1.0.4 now.
