### ISSUE TITLE
Ship proguard rules in the aar?

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ThreeTenABP#4]
Would require:
 * Consensus on rules to include. Ideally would be as limited as possible to allow _some_ stripping to occur, where feasible.
 * Enabling proguard for the instrumentation tests
 * Tests which exercise as much of the API as easily as possible to validate the rules.

**Comment by bryanstern** [comment]
```# Threeten backport
-dontwarn java.util.spi.LocaleServiceProvider
-dontwarn sun.util.calendar.*
-keep class org.threeten.bp.zone.*```

I haven't had a chance to exercise these a ton, but they have me building. Found here https://github.com/ThreeTen/threetenbp/issues/12#issuecomment-50152267

**Comment by JakeWharton** [comment]
Bundled rules can be done with:
```groovy
  buildTypes {
    release {
      minifyEnabled true
      proguardFiles 'proguard.cfg'
      consumerProguardFiles 'proguard.cfg'
    }
  }
```

**Comment by JakeWharton** [comment]
> ```
> -keep class org.threeten.bp.zone.*
> ```

@bryanstern Why did you add this?

**Comment by JakeWharton** [comment]
I got this far: https://github.com/JakeWharton/ThreeTenABP/compare/jw/PROGUARD_IS_PAIN

Proguard is pain.

**Comment by bryanstern** [comment]
Good catch, I don't think `-keep class org.threeten.bp.zone.*` is needed. I misinterpreted some of the build errors that were spit out. I'm not having any issues without it.

**Comment by bryanstern** [comment]
I'll kick the tires tomorrow on that code, but it looks good. 👍

**Comment by JakeWharton** [comment]
I removed it. I also removed `-dontwarn java.util.spi.LocaleServiceProvider` which isn't used anywhere in 310BP.

**Comment by JakeWharton** [comment]
Released in 1.0.2.

**Comment by cp949** [comment]
```
## build.gradle file
compile 'com.jakewharton.threetenabp:threetenabp:1.0.3'
```


# FIRST TEST
```
#  proguard file for Threeten backport
-dontwarn java.util.spi.LocaleServiceProvider
-dontwarn sun.util.calendar.*
-keep class org.threeten.bp.zone.*
-keep class org.threeten.bp.*

android test code:
	Log.e(LOG_TAG, "toJson:" + new Gson().toJson(LocalDateTime.now()));

console output :
	toJson:{"a":{"a":2015,"b":11,"c":14},"b":{"b":18,"c":47,"d":37,"e":79000000}}
```

# SECOND TEST
```
# proguard file for Threeten backport
-dontwarn java.util.spi.LocaleServiceProvider
-dontwarn sun.util.calendar.*
-keep class org.threeten.bp.zone.*
-keep class org.threeten.bp.*
-keepclassmembers class org.threeten.bp.** { *; }


android test code:
	Log.e(LOG_TAG, "toJson:" + new Gson().toJson(LocalDateTime.now()));

console output :
	toJson:{"date":{"day":14,"month":11,"year":2015},"time":{"hour":18,"minute":51,"nano":394000000,"second":14}}
```

I think you should add the following line in proguard file.
-keepclassmembers class org.threeten.bp.** { *; }

**Comment by JakeWharton** [comment]
That effectively disables proguard for the whole library. If you don't want
it obfuscated, turn off obfuscation on it in your own config.

**Comment by cp949** [comment]
My server uses the java8 and LocalDateTime.
The json messages received from the server can not handle because threeten-Proguard on Android.

I probably always will be off the threeten-proguard.

**Comment by JakeWharton** [comment]
If you are JSON serializing the objects then that is something specific to
your application and should be addressed in your proguard config. The
library does not concern itself with retaining field names by default
because most people will not be doing this.
