### ISSUE TITLE
need an update to the TZDB.dat file for Asia/Yangon

### ISSUE THREAD

**Issue by kenyee** [JakeWharton/ThreeTenABP#43]
Apparently, the Asia/Rangoon TZ has been renamed to Asia/Yangon in the official IANA DB: ftp://ftp.iana.org/tz/tzdb/asia

but ThreeTenABP's TZDB.dat file still references Asia/Rangoon.

Some Android phones still return their locale as Asia/Rangoon and their OS's will never be updated, so ideally, ThreeTenABP would alias the Yangon and Rangoon TZs.

**Comment by JakeWharton** [comment]
I'm pulling in the TZDB from ThreeTenBP 1.3.3. In the future, please send TZDB update requests to ThreeTenBP directly as this project will not update the rules before it does.
