### ISSUE TITLE
DateTimeFormatter not properly formatting month and day of week string

### ISSUE THREAD

**Issue by tir38** [JakeWharton/ThreeTenABP#48]
I'm trying to format a ZonedDateTime as `Tuesday, March 19`. But I'm only ending up with `Tue, 3 19`.

I'm pretty sure I'm following the [formatting string guidelines](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) correctly.

```
DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("EEEE, MMMM d");
String dateString = zonedDateTime.format(dateFormat);
```

The bizarre part is that when I unit test this code it works fine, but running on an actual Android device truncates day of the week and uses integer for month.

**Comment by JakeWharton** [comment]
You should file an issue on [ThreeTenBP][1]. This project only provides the timezone database to that library in a way compatible with Android.

 [1]: https://github.com/ThreeTen/threetenbp

**Comment by tir38** [comment]
Great thx. Sorry for the inconvenience.

Breadcrumb to report on ThreeTen [here](https://github.com/ThreeTen/threetenbp/issues/62)
