### ISSUE TITLE
Look into JapaneseEra implementation implications

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ThreeTenABP#5]
It relies on `sun.util.calendar` classes in a non-optional way.

**Comment by JakeWharton** [comment]
Ok so this loads the japanese eras defined in the JDK since they are subject to change: https://en.wikipedia.org/wiki/Japanese_era_name#Neng.C5.8D_in_modern_Japan

**Comment by Dunemaster** [comment]
This is fixed in ThreeTen 1.3.3

https://github.com/ThreeTen/threetenbp/commit/c024682ae92154e8de9226c0bccde8ce18f9c0bd

**Comment by JakeWharton** [comment]
Perfect! Will update today.

**Comment by JakeWharton** [comment]
2d06611ffc8c5f4d34d457d70edd2d16887da59a
