### ISSUE TITLE
Use Android TimeZone instead of Database

### ISSUE THREAD

**Issue by metinkale38** [JakeWharton/ThreeTenABP#51]
Hey,

i wonder, whether there is a reason to use the Timezones Database instead of the Android Timezones directly? 
Of course, it might be sometimes good to have a newer database version, but most of the time it makes problem, when they are not in sync... Apps using Joda will show another "Current Local Time" than the OS.

As solution i had a TimeZone Provider for JodaTime: https://github.com/dlew/joda-time-android/issues/165
it should be possible to adapt it similiar to this library

i am using it for a while, and did not have any issues till now...

it might be a good idea, to make this default (or at least configurable)

or is there something i miss, why thats not a good idea?

**Comment by JakeWharton** [comment]
You can already do this. The threetenbp library is pluggable with timezone providers. This library is just a different packaging of their tzdb for Android with a provider that loads it from assets instead of as a Java resource.
