### ISSUE TITLE
Provide sources for documentation ?

### ISSUE THREAD

**Issue by NinoDLC** [JakeWharton/ThreeTenABP#55]
Android Studio's javadoc support is great and helpful but since it's a decompiled lib, there's no javadoc available. 

Could you provide the sources with the Javadoc included so we could attach it to the decompiled lib ? :)

**Comment by JakeWharton** [comment]
The source and javadoc for this library is provided. You're likely
referring to the threetenbp artifact itself which uses a qualifier on the
dependency and prevents the source and javadoc from being found. This isn't
a problem with this library. You should file a bug on JetBrains' YouTrack
for IntelliJ IDEA for this support. Or file on threetenbp to publish source
and javadoc jars for the qualified artifact to Maven Central.

**Comment by Saketme** [comment]
Are there any workarounds that I can use in the meanwhile to be able to view source in Android Studio?

**Comment by JakeWharton** [comment]
You can download the source jar and attach it manually into your IDE.

**Comment by NinoDLC** [comment]
Nope, doesn't work.

**Comment by Saketme** [comment]
@NinoDLC make sure you download sources for ThreeTen and not ThreeTenABP.
