### ISSUE TITLE
TZDB.dat duplicate zip entry in release APK

### ISSUE THREAD

**Issue by blackberry2016** [JakeWharton/ThreeTenABP#56]
compile group: 'org.threeten', name: 'threetenbp', version: '1.3.5', classifier: 'no-tzdb'

My threetenbp version is 1.3.5

**Comment by JakeWharton** [comment]
That isn't this library. The dependency declaration for this library is available in the README.

**Comment by blackberry2016** [comment]
@JakeWharton I use this library by modifying the source code and change the threetenbp version from [1.3.3 to 1.3.5](compile group: 'org.threeten', name: 'threetenbp', version: '1.3.3', classifier: 'no-tzdb')

**Comment by JakeWharton** [comment]
Use 1.3.6 then. The jar for 1.3.5 was not packaged correctly.
