### ISSUE TITLE
Add Duration methods for days, hours, minutes, seconds, etc.

### ISSUE THREAD

**Issue by tprochazka** [JakeWharton/ThreeTenABP#57]
Would be great to integrate this to the backport:
https://bugs.openjdk.java.net/browse/JDK-8142936

**Comment by JakeWharton** [comment]
This library only exposes a single API. You want https://github.com/ThreeTen/threetenbp

**Comment by tprochazka** [comment]
By "Single API" you mean just JSR-310 and this Jave 9 update is jsr379 already.
Just https://github.com/ThreeTen/threetenbp is not optimized for Android.
I don't know how big performance issue it is.
I just need to format Duration in some human readable format like 1 day, 20 hours and 10 minutes.

**Comment by JakeWharton** [comment]
No I mean the `AndroidThreeTen` class. Everything else is from threetenbp.

**Comment by tprochazka** [comment]
Ohh sorry. I did not realize that :-) LOL
