### ISSUE TITLE
Comparison to joda-time-android

### ISSUE THREAD

**Issue by feinstein** [JakeWharton/ThreeTenABP#61]
I am sorry to ask you this bluntly, but how does your solution compares to:
https://github.com/dlew/joda-time-android

I am evaluating a good way to implement JSR-310 on old devices and I can't figure how you two are different and which one to choose.

**Comment by FarbodSalamat-Zadeh** [comment]
It's in the README, I think:

https://github.com/JakeWharton/ThreeTenABP/blob/master/README.md#why-not-use-joda-time

**Comment by JakeWharton** [comment]
Yep, thanks.

**Comment by feinstein** [comment]
@JakeWharton, I have read the README before, and I did it again, I can't find anything explaining about:

https://github.com/dlew/joda-time-android

Maybe I am the one making the confusion, but I want to make it clear that link is NOT Joda Time, it's an implementation that looks a lot like yours as a solution to the Joda Time problems.

**Comment by feinstein** [comment]
Ok, apparently joda-time-android is really a complete wrap of the entire Joda-Time, now I understand your answer, I am sorry, I thought they too simplified the method count.

**Comment by AndroidDeveloperLB** [comment]
What's the difference with this library though:
https://github.com/ThreeTen/threetenbp

?

**Comment by dlew** [comment]
https://github.com/JakeWharton/ThreeTenABP/blob/master/README.md#why-not-use-threetenbp

**Comment by AndroidDeveloperLB** [comment]
how did I miss that...
Thank you.

**Comment by AndroidDeveloperLB** [comment]
But it seems like their library is more frequently updated. Is the one here based on it? Or is it independent ?

**Comment by AndroidDeveloperLB** [comment]
In fact I don't see any code here that's related to LocalDate at all. Where's the code? How could it be?
