### ISSUE TITLE
Could not find threetenbp-no-tzdb.jar

### ISSUE THREAD

**Issue by stranchand** [JakeWharton/ThreeTenABP#64]
Hello,

We are using your adaptation of the JSR-310 backport for Android, but since a few days our project could not be build anymore.

We have this error : 
Error:Could not find threetenbp-no-tzdb.jar (org.threeten:threetenbp:1.3.3).

Is this dependency still alive ?

**Comment by JakeWharton** [comment]
Yep. Maven central is immutable so dependencies will never disappear: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.threeten%22%20AND%20a%3A%22threetenbp%22.

**Comment by stranchand** [comment]
On mvnrepository wee can the your lib : 
https://mvnrepository.com/artifact/com.jakewharton.threetenabp/threetenabp/1.0.5
On the POM file we can see the no-tzdb dependency, but it's not available on mvnrepository.

Is that normal ?

**Comment by JakeWharton** [comment]
That website is not Maven central. The dependency is present in Maven
central:
http://search.maven.org/#artifactdetails%7Ccom.jakewharton.threetenabp%7Cthreetenabp%7C1.0.5%7Caar

**Comment by michael-reed-hampton** [comment]
For those that find this:
Removing the 'threeten' from my local maven repo and re-running my build fixed this.
rm -r ~/.m2/repository/org/threeten
