### ISSUE TITLE
Question: Where's the code exactly?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JakeWharton/ThreeTenABP#66]
It is said this library is better than [ThreeTenBP repo](https://github.com/ThreeTen/threetenbp), [here](https://github.com/JakeWharton/ThreeTenABP/blob/master/README.md#why-not-use-threetenbp) .

So I was curious and looked at the repo's files, but I don't see a lot at all, especially not of LocalDate, which I somehow use by using this repo.

How could it be?

Is it somehow using the threetenbp library, yet with some changes applied?

If so, is it frequently updated like it? Maybe even auto-updated ? I ask this because I notice that the threetenbp library seems updated more recently (has some files updated 6 months ago), yet here it's not (newest files updated 11 months ago) .

**Comment by JakeWharton** [comment]
The code is from ThreeTenBP. This library merely repackages the timezone database.

https://github.com/JakeWharton/ThreeTenABP/blob/5bf6fe3c7940297d05e71726ae8a2b8919792ca3/threetenabp/build.gradle#L4

**Comment by AndroidDeveloperLB** [comment]
Latest version is 1.3.6 , no?
How does it do the re-packaging?
The goal is to avoid jar file, as the description says: "JAR resource for loading timezone information" ?

**Comment by JakeWharton** [comment]
The timezone DB is in the assets folder of this libarry.

**Comment by AndroidDeveloperLB** [comment]
Nice.
But what about the version? Shouldn't it be 1.3.6 ?
Also, I think that since this repo is based on the other one, maybe use the same exact version numbers?

**Comment by JakeWharton** [comment]
You're free to depend on a newer version of threetenbp directly if you
require its updates. This library won't be updating the version for every
threetenbp release.

**Comment by AndroidDeveloperLB** [comment]
Makes sense.
I have no idea what's new there, so I don't know if it'll worth it. I just like most updated one, to avoid bugs, have better functions, and better performance...

Do you update your repo every now and then?

**Comment by JakeWharton** [comment]
Yep. Feel free to send a PR to update the version anytime there's a new one.

**Comment by AndroidDeveloperLB** [comment]
ok here:
https://github.com/JakeWharton/ThreeTenABP/pull/70

repo here:
https://github.com/AndroidDeveloperLB/ThreeTenABP

**Comment by AndroidDeveloperLB** [comment]
It could be nice if you also update the version of your repo, to be identical to the one it's based on.
