### ISSUE TITLE
Cannot use Joda's methods

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/ThreeTenABP#7]
Hi,
I used to be able to use Jodatime's `DateTime` and `ISODateTimeFormat`.  Now, I cannot with ThreeTenABP.  Is there an equivalent api for these calls?

Thanks,
Igor

**Comment by JakeWharton** [comment]
This library is just an adaptation of ThreeTenBP to Android. If you want information on how to use JSR 310 / ThreeTenBP check out [their list of links][1].

 [1]: http://www.threeten.org/links.html
