### ISSUE TITLE
Update TZ data

### ISSUE THREAD

**Issue by PaulWoitaschek** [JakeWharton/ThreeTenABP#73]
I have crashes because the TZ db of the backport project is outdated:

https://github.com/ThreeTen/threetenbp/issues/85

Is it possible to update the tz data regularly here instead?

**Comment by JakeWharton** [comment]
No. This library is merely a re-packaging of the tzdb present in ThreeTenBP. Once it updates, this project can be updated.

**Comment by gabrielittner** [comment]
Updating ThreeTenABP to use the latest ThreeTenBP should add support for America/Punta_Arenas. 

The current ThreeTenABP and ThreeTenBp 1.3.3 use 2016j, America/Punta_Arenas was added in 2017a, and starting with 1.3.5 ThreeTenBP uses 2017b.

**Comment by jakob-grabner** [comment]
I also have crashes because of `Unknown time-zone ID: America/Punta_Arenas`. A new release of ThreeTenABP using the latest ThreeTenBP would be really helpful!

**Comment by JakeWharton** [comment]
Breaking news: I have some free time today. Let me see what I can do.
