### ISSUE TITLE
Alternative way to convert to UTC doesn't seem to work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JakeWharton/ThreeTenABP#77]
Suppose you have the current time in the current time zone, as such:

    LocalDateTime now = LocalDateTime.now();

or as such:

        Calendar cal = Calendar.getInstance();
        LocalDateTime now = LocalDateTime.of(cal.get(Calendar.YEAR), cal.get(Calendar.MONTH) + 1, cal.get(Calendar.DAY_OF_MONTH), cal.get(Calendar.HOUR_OF_DAY),
                cal.get(Calendar.MINUTE), cal.get(Calendar.SECOND), cal.get(Calendar.MILLISECOND) * 1000000);

And now you wish to convert it to UTC. One way to do it is as such :

    LocalDateTime nowInUtc = now.atZone(ZoneId.systemDefault()).withZoneSameInstant(ZoneId.of("UTC")).toLocalDateTime();

But according to what I've found, this should also work:

    LocalDateTime alternativeNowInUtc = now.atZone(ZoneOffset.ofTotalSeconds(TimeZone.getDefault().getRawOffset() / 1000)).withZoneSameInstant(ZoneId.ofOffset("UTC", ZoneOffset.ofHours(0))).toLocalDateTime();

Yet for some reason the second way to do it is off by a whole hour.

How come?

**Comment by JakeWharton** [comment]
This is a general usage question of the ThreeTenBP library and not specific to ThreeTenABP. If it's a usage question your best bet is to ask on StackOverflow. If you think you have found a bug in the library or tzdb, file a bug on the upstream ThreeTenBP project.

**Comment by AndroidDeveloperLB** [comment]
Makes sense. Here:
https://stackoverflow.com/q/49770822/878126
