### ISSUE TITLE
MinSDK higher than needed

### ISSUE THREAD

**Issue by ligi** [JakeWharton/ThreeTenABP#8]
Is there a reason I do not see to have minSDK on 15? It seems to also compile with 5:

diff --git a/build.gradle b/build.gradle
index 7f365e4..87c8e03 100644
--- a/build.gradle
+++ b/build.gradle
@@ -14,7 +14,7 @@ allprojects {
 }
 
 ext {
-  minSdkVersion = 15
+  minSdkVersion = 5
   compileSdkVersion = 22
   buildToolsVersion = '22.0.1'

**Comment by JakeWharton** [comment]
The upstream library is backported to Java 6 so the very least that is viable would be 9.

At this point, there's really no point in supporting anything less than 15, though. Unless there's a compelling reason beyond the fact that it simply works I'd prefer not to encourage people to support users of no value on these ancient API levels.

**Comment by ligi** [comment]
I wanted to switch PassAndroid from Joda-Time to ThreeTenABP and noticed the minSDK this way - PassAndroid is minSDK 9 and I would cut of over 4000 users when increasing the minSDK - so I will stick with Joda-Time for now

**Comment by JakeWharton** [comment]
If you have 5000 users total then that is smart. If you have 1,000,000, though, then you are wasting your effort! Leave them in peace on an old version and tailor to your high-value users on modern phones. I can't imagine the monetization strategy of users on a phone from 3 years ago yields enough to warrant dedicating any amount of engineering effort to supporting them. Plus Android 2.x is so ugly!

As the README and linked blog post from Stephen says, if you are using Joda and it works there's little reason to put in the effort to switch libraries.

**Comment by unrulygnu** [comment]
> users of no value

With all due respect, that's a rather myopic snub.

As many of us have been informed (particularly with regard to device testing), there is a world outside multi-six-figure salaries, stock options, Teslas, first-class seats, molecular gastronomy, the use of "ask" as a noun, and safe spaces.  And this world comprises billions of people.

I've lived in places in this world where tens of thousands of people lacked electric power in their homes, yet they had and relied on mobile devices, recharging daily in town centers where there was power. They use apps to learn stuff, buy stuff, connect with others, be entertained:  a familiar use case. 

People in places like this don't have the luxury to jump devices every year or two. Actually, that even goes for thousands (if not millions) in the USA; they stretch these devices til the last pixel goes dark.

And not every app comes with a monetization strategy. Or an exit strategy. Or incubators or VC's or angels, oh my.  Some app developers just try to solve a problem, or make something better/easier -- like maintainers of a number of open source projects (wink wink, nudge nudge) -- and they sometimes try to be inclusive of the people in this other world.

For this reason, I humbly request that you reconsider your decision.  If minSdk 9 doesn't require any further engineering effort in this valuable library, then please make it available to the developers who serve these people.  Thanks for your consideration, as well as all your contributions to the stack. <3

**Comment by gabrielittner** [comment]
If it does work on lower APIs without any code changes just add `<uses-sdk tools:overrideLibrary="com.jakewharton.threetenabp" />` to your manifest.

**Comment by kael-shipman** [comment]
@unrulygnu So glad to see someone else who's left the Matrix ;).

@gabrielittner Thanks for the tip. Worked for me.

@JakeWharton Thank you for supplying and maintaining this (and @unrulygnu makes an excellent point)).
