### ISSUE TITLE
Cant start application due to ThreeTenABP /dalvikvm: Could not find class

### ISSUE THREAD

**Issue by Crakeh** [JakeWharton/ThreeTenABP#82]
I experienced this bug only on Android, which api level is below 20. On android with api levels 16 - 19, while im trying to run the app. Application is logging in infinity loop this error: 

E/dalvikvm: Could not find class 'org.threeten.bp.zone.TzdbZoneRulesProvider', referenced from method com.jakewharton.threetenabp.AndroidThreeTen.init

I've tried cleaning the project rebuilding the project, but is weird that Android oreo has no problem and the aplication is running.

in my gradle im using 
compile "com.jakewharton.threetenabp:threetenabp:$rootProject.threetenabpVersion"

with $rootProject.threetenabpVersion = '1.0.5', upgrading to 1.0.6, doest resolve the issue

**Comment by JakeWharton** [comment]
Are you using multidex? Is that type in your APK?

**Comment by Crakeh** [comment]
Yes, im using in my gradle multiDexEnabled true as well. Have you ever met with such a error? Is there connection with multidex?

**Comment by JakeWharton** [comment]
Sounds like the necessary classes aren't in the main dex

**Comment by Crakeh** [comment]
Thank you, I spent almost "my entire life" on this issue.  I use MultiDex.install(this), but in my application I have more modules and I have to add it to another class as well. Thanks for your hint. Many thanks again :))))
