### ISSUE TITLE
Wrong timezone parsing

### ISSUE THREAD

**Issue by Diolor** [JakeWharton/ThreeTenABP#83]
Might also be a issue in the threeten's timezone .dat rather than this lib.

System:
               
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

For this code:

```java
    String dateString = "2015,7,21,0,0,0,GMT+02:00";
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy,M,d,H,m,s,z", Locale.US);
		ZonedDateTime parsed = ZonedDateTime.parse(dateString, formatter);
		System.out.println("Parsed: " + parsed);
```

Output is:

    2015-07-21T00:00+03:00[Asia/Famagusta]

Expectation:

    2015-07-21T00:00+02:00[Etc/GMT-2]

This happens only when running tests from gradle terminal command. Running the same test in Android Studio passes.

**Comment by JakeWharton** [comment]
Seems like the timezones aren't being loaded. Is this a JVM test or an instrumentation test? You probably want to use the normal threetenbp depedency for JVM tests and ThreeTenABP only for things that run on Android.

**Comment by Diolor** [comment]
JVM. It happens with threetenbp too so I will move it there
