### ISSUE TITLE
Can I use time.java from Java library in Android project?

### ISSUE THREAD

**Issue by nuxzero** [JakeWharton/ThreeTenABP#86]
I'm not sure. Is **ThreeTenABP** cover the case usage `time.java` from a Java library that has the model properties using `time.java` e.g. `Instant`, `ZonedDateTime` inside Android project or not?

What I see right now, the Android project cannot get the `java.time` properties in Java library without change minimum SDK version to 26.

Or there are another solution to deal with `java.time` without upgrade minimum SDK?

**Comment by nuxzero** [comment]
Sorry, my question may be not quite clear. The Java library that I mention to is a dependency that put into the Android project. It's not created by me from inside Android project. So, the Java library is out of my control. I can't really use ThreeTenABP in the Java library.

**Comment by JakeWharton** [comment]
If the library uses `java.time.*` APIs then there is nothing you can do other than avoid them and hope for legacy overloads that use `long`+`TimeUnit`.

If you use the Bazel build system it can desugar `java.time.*` APIs: https://blog.bazel.build/2018/07/19/java-8-language-features-in-android-apps.html
