### ISSUE TITLE
Flexible DST changes for countries seem to be off

### ISSUE THREAD

**Issue by djustix** [JakeWharton/ThreeTenABP#88]
Aiming to offer support to older Android versions, I'm using this library successfully for a while in a production app. Turns out that some countries are fairly flexible in when they think it's the right time to switch DST on/off. I've been getting reports (a lot) from Brasil that times are an hour off.

The topic is well-known within Brazil, but never reached me. This link seems to confirm the story:
https://www.timeanddate.com/time/zone/brazil/brasilia. I figured the issue would be in TZDB.dat, but I can't confirm that as I'm not fully sure what format that is and in what kind of editor I should open it to make more sense beyond the list of regions.

Anyway, using the equivalents from the `java.time` package returns the expected times:
```
printJavaa = "2018-10-22T19:52:37.350"
printThree = "2018-10-22T20:52:37.415"
```
_(These are the print outputs for LocalDateTime.now() from the respective packages)_

Now I guess this is a fairly unique thing to happen, so I'm not really complaining. I'm just looking for some insights on how to cope with this. It's fairly easy to apply remotely configurable hacks that make you cry when implementing it, but for that same reason I hope a more sweet solution is within reach.

Thanks in advance for any suggestions on this topic.

**Comment by JakeWharton** [comment]
The timezone database comes from https://github.com/ThreeTen/threetenbp. This library just repackages it for consumption on Android. Any issues with the data should be taken up with that library. I release new versions of this library when threetenbp has releases with new timezone database information.
