### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/ThreeTenABP#9]
Hi,
I cannot `    compile 'com.jakewharton.threetenabp:threetenabp:1.0.1'`.  My test project throws a build error:
> Error:Gradle: Execution failed for task ':app:mergeDebugAssets'.
> [org/threeten/bp/TZDB.dat] E:\git\WORK\app\build\intermediates\exploded-aar\com.jakewharton.threetenabp\threetenabp\1.0.1\assets\org\threeten\bp\TZDB.dat	[org/threeten/bp/TZDB.dat] E:\git\WORK\app\build\intermediates\exploded-aar\com.jakewharton.threetenabp\threetenabp\1.0.1\assets\org\threeten\bp\TZDB.dat: Error: Duplicate resources

Please advise.

**Comment by IgorGanapolsky** [comment]
Nevermind, looks like I had to clean and rebuild my project.

**Comment by AdamMTGreenberg** [comment]
I still get this using RobolectricGradleTestRunner - is anyone else seeing this at all? Or should I just move to the JuintTestRunner nowadays?
