### ISSUE TITLE
Utils and getEventTimeZone not recognized

### ISSUE THREAD

**Issue by BobbyRuby** [JakeWharton/ThreeTenABP#93]
My gradle is correct per instructions, I have it initiated inside onCreate...
```
 private static ZoneId getZoneId() {
        if (showLocal || Utils.isEmpty(getEventTimeZone()))
            return ZoneId.systemDefault();
        else
            return ZoneId.of(getEventTimeZone());
    }
```

**Comment by JakeWharton** [comment]
It's not clear what the problem is. `Utils` and `getEventTimeZone` are your things, not the library's.

**Comment by BobbyRuby** [comment]
I used this tutorial so I'm confused... Sorry for my ignorance.   Please help me out if it doesn't take too long.

Is there a function reference I can use?  I just need to get the current date... that is all.

https://blog.fossasia.org/using-threetenabp-for-time-zone-handling-in-open-event-android/

**Comment by JakeWharton** [comment]
`LocalDateTime.now()` will return the current date.

**Comment by BobbyRuby** [comment]
Holy shit... I just spent 2 hours trying to figure out what the hell to do.. Thank you!
