### ISSUE TITLE
Release Signed .APK App!

### ISSUE THREAD

**Issue by mgsofteng** [JakeWharton/ThreeTenABP#95]
I'm trying to generate my (signed) app APK which is linked to our custom API library. This custom library has dependency on the "threetenABP" library, using the line below:

implementation 'com.jakewharton.threetenabp:threetenabp:1.1.1'

But I get these warning errors:

apiservice.BtMeterService: can't find referenced class com.jakewharton.threetenabp.AndroidThreeTen
util.Utils: can't find referenced class org.threeten.bp.ZoneOffset 
util.Utils: can't find referenced class org.threeten.bp.ZonedDateTime |  
util.Utils: can't find referenced class org.threeten.bp.format.DateTimeFormatter |  
util.Utils: can't find referenced class org.threeten.bp.ZonedDateTime |  
util.Utils: can't find referenced class org.threeten.bp.LocalDateTime |  
util.Utils: can't find referenced class org.threeten.bp.ZoneId |  
util.Utils: can't find referenced class org.threeten.bp.LocalDateTime |  
util.Utils: can't find referenced class org.threeten.bp.ZoneId |  
util.Utils: can't find referenced class org.threeten.bp.ZonedDateTime |  
util.Utils: can't find referenced class org.threeten.bp.ZoneId |  
there were 21 unresolved references to classes or interfaces. |  
Exception while processing task java.io.IOException: Please correct the above warnings first. |

**Comment by JakeWharton** [comment]
This is ProGuard complaining that it can't actually find the types from the library which would indicate that it's not properly included. Without more information it's impossible to diagnose, but it's not a problem with the library but a build system configuration problem. You can use the `dependencies` task to check to make sure the library and threetenbp are actually on your classpath.
